name: Build and Deploy API
on: 
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    name: Build API
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

# DOCKERHUB

#    - name: Build the Docker container image
#      run: docker build ./api -f ./api/Dockerfile -t techhead/api.anketa.info:latest
      
#    - name: Push the image to hub.docker.com
#      run: |
#        docker login -u techhead -p "${DOCKER_HUB_PASS}"
#        docker push techhead/api.anketa.info:latest
#      env:
#        DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}

# Github Package Registry (GPR)

    - name: Build the Docker container image
      run: docker build ./api -f ./api/Dockerfile -t docker.pkg.github.com/marley-nodejs/mern-stack-front-to-back-v2.0/api.anketa.info:latest
      
    - name: Push the image to Github Package Registry (GPR)
      run: |
        docker login docker.pkg.github.com -u publisher -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
        echo "-----------"
        echo "-----------"
        echo "-----------"
        docker --debug --log-level "debug" push docker.pkg.github.com/marley-nodejs/mern-stack-front-to-back-v2.0/api.anketa.info:latest
        echo "-----------"
        echo "-----------"
        echo "-----------"
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
