name: Build and Deploy Proxy
on: 
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    name: Build Proxy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      
# DOCKERHUB      
      
#    - name: Build the Docker container image
#      run: docker build ./proxy -f ./proxy/Dockerfile -t techhead/proxy:latest
#    - name: Push the image to hub.docker.com
#      run: |
#        docker login -u techhead -p "${DOCKER_HUB_PASS}"
#        docker push techhead/proxy:latest
#      env:
#        DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}

# Github Package Registry (GPR)   

    - name: Build the Docker container image
      run: docker build ./proxy -f ./proxy/Dockerfile -t docker.pkg.github.com/marley-nodejs/mern-stack-front-to-back-v2.0/proxy:latest

    - name: Push the image to Github Package Registry (GPR)
      run: |
        docker login docker.pkg.github.com -u publisher -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
        docker push docker.pkg.github.com/marley-nodejs/mern-stack-front-to-back-v2.0/proxy:latest
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
