name: Build and Deploy Client
on: 
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    name: Build Client
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker container image
      run: docker build ./proxy -f ./proxy/Dockerfile -t techhead/proxy:latest
    - name: Push the image to hub.docker.com
      run: |
        docker login -u techhead -p "${DOCKER_HUB_PASS}"
        docker push techhead/proxy:latest
      env:
        DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}